get all save changes (dispite of the month, now the service will give…
Monasafer/bff-core pull request #16
Opened 2022-01-22 23:06 UTC by ferlefloth

… you all the data)

2022-01-22 23:08 UTC, federicomarilungo requested changes
siguen andando los tests? seguro hay q modificarlo, con suerte anda pero ahora ya no necesitas mandar el month

2022-01-22 23:13 UTC, ferlefloth commented
> siguen andando los tests? seguro hay q modificarlo, con suerte anda pero ahora ya no necesitas mandar el month

Si , se podría sacar en el testo. Ahí lo mando

2022-01-23 00:22 UTC, federicomarilungo commented on test/save.test.js
> +            //'url': url + 'save?month=' + month,
borrar comentarios

2022-01-23 00:24 UTC, federicomarilungo requested changes
comentarios + pregunta

si al endpoint le mandas el month, lo ignora y responde o tira error? 

esto para saber si el front rompería ( en otras palabras si el cambio es retrocompatible )

2022-01-23 00:25 UTC, ferlefloth commented on test/save.test.js
> +            //'url': url + 'save?month=' + month,
listo

2022-01-23 00:27 UTC, ferlefloth commented
> 

Cuando haces el request con el month , responde e ignora el parametro. Devuelve toda la data.
Prueba: 
![image](https://user-images.githubusercontent.com/57419807/150659887-7d8e5e67-bc93-48d9-bde1-7901f0969da9.png)

2022-01-23 01:32 UTC, federicomarilungo approved these changes

2022-01-23 01:49 UTC, merged